# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://github.com/fgrehm/vagrant-cachier#quick-start
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  # Kehitystyön tietokantapalvein
  config.vm.define "db" do |db|
    db.vm.box = "CentOS-6.5-x86_64-v20140311.box"
    db.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140311.box"

    db.vm.synced_folder "../env", "/env"
    if File.directory?("../konversio")
      db.vm.synced_folder "../konversio", "/dumps"
    end
    db.vm.provision "shell", inline: "cd /env && ./dev-db.sh"

    # local port 2345 -> vm port 5432
    db.vm.network "forwarded_port", host: 9876, guest: 5432
    db.vm.network "private_network", ip: "192.168.50.151"
  end
end
